all: folders server client
server: bin/monitor
client: bin/tracer
folders:
	@mkdir -p src obj bin tmp
bin/monitor: obj/monitor.o obj/InfoStructArray.o
	gcc -g obj/monitor.o obj/InfoStructArray.o -o bin/monitor
obj/monitor.o: src/monitor.c src/InfoStructArray.h
	gcc -Wall -g -c src/monitor.c -o obj/monitor.o
bin/tracer: obj/tracer.o obj/InfoStructArray.o
	gcc -g obj/tracer.o obj/InfoStructArray.o -o bin/tracer
obj/InfoStructArray.o: src/InfoStructArray.c src/InfoStructArray.h
	gcc -g -c src/InfoStructArray.c -o obj/InfoStructArray.o	
-o obj/tracer.o: src/tracer.c
	gcc -Wall -g -c src/tracer.c -o obj/tracer.o

clean:
	rm -f obj/* tmp/* bin/{tracer,monitor}
